#!/bin/bash

function recurse {
    local i

    if [ $1 -gt 0 ]; then
        for i in `seq 1 $(($1-1))`; do
            if [ ${4:i-1:1} -lt 1 ]; then
                echo -n '  '
            else
                echo -n '│ '
            fi
        done

        if [ ${4:${#4}-1:1} -eq 0 ]; then
            echo -n "└─"
        else
            echo -n "├─"
        fi
    fi

    OLD_IFS=$IFS
    IFS=$'\n'
    echo -e "$(pushd $2 &>/dev/null; ls --color=always -dF $3; popd &>/dev/null)$(if [ -h $2$3 ]; then echo -n " → $(readlink $2$3)"; fi)"

    if [ -d $2$3 ] && ! [ -h $2$3 ]; then
        i=0
        local limit=$(ls -1 $2$3 | wc -l)
        for entry in $(ls -1 $2$3); do
            if [ $i -lt $((limit-1)) ]; then
                next=1
            else
                next=0
            fi
            recurse $(($1+1)) $2$3/ $entry $4$next
            i=$((i+1))
        done
    fi
    IFS=$OLD_IFS
}

if [ $# -lt 1 ]; then
    recurse 0 '' "." ''
else
    for arg in "$@"; do

        if [ "$arg" == "/" ]; then
            echo "I will not list /!"
            continue
        fi

        recurse 0 '' "${arg%/}" ''
    done
fi
