#!/bin/bash

#
# © Copyright 2013 by Edgar Kalkowski <eMail@edgar-kalkowski.de>
#
# The program lstree is free software; you can redistribute it and/or modify it under the terms of
# the GNU General Public License as published by the Free Software Foundation; either version 3 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program. If
# not, see <http://www.gnu.org/licenses/>.
#

function recurse {
    local i

    if [ $1 -gt 0 ]; then
        for i in `seq 1 $(($1-1))`; do
            if [ ${4:i-1:1} -lt 1 ]; then
                echo -n '  '
            else
                echo -n '│ '
            fi
        done

        if [ ${4:${#4}-1:1} -eq 0 ]; then
            echo -n "└─"
        else
            echo -n "├─"
        fi
    fi

    OLD_IFS=$IFS
    IFS=$'\n'
    echo -e "$(pushd $2 &>/dev/null; ls --color=always -dF $3; popd &>/dev/null)$(if [ -h $2$3 ]; then echo -n " → $(readlink $2$3)"; fi)"

    if [ -d $2$3 ] && ! [ -h $2$3 ]; then
        i=0
        local limit=$(ls -1 $2$3 | wc -l)
        for entry in $(ls -1 $2$3); do
            if [ $i -lt $((limit-1)) ]; then
                next=1
            else
                next=0
            fi
            recurse $(($1+1)) $2$3/ $entry $4$next
            i=$((i+1))
        done
    fi
    IFS=$OLD_IFS
}

if [ $# -lt 1 ]; then
    recurse 0 '' "." ''
else
    for arg in "$@"; do

        if [ "$arg" == "/" ]; then
            echo "I will not list /!"
            continue
        fi

        recurse 0 '' "${arg%/}" ''
    done
fi
